# Downstream External API Services URLs (Mocks running on WireMock port 8085)
app.cards-service.base-url=http://localhost:8085
app.payments-service.base-url=http://localhost:8085

# Server configuration
server.port=8080
